#!/usr/bin/env bash
SCRIPTS_DIR=$(dirname $0)
FILE_TO_COPY=$(realpath "$1")
NODE_NAMES="$($SCRIPTS_DIR/node_names $2)"

echo "will copy $FILE_TO_COPY to nodes $(echo $NODE_NAMES | xargs)"

echo ""
echo ""
echo ""
echo ""

read -n 1 -s -r -p "Press any key to continue..."
echo ""
echo ""

parallel vagrant scp $FILE_TO_COPY {}:~/ ::: $NODE_NAMES