#!/usr/bin/env bash
SCRIPTS_DIR=$(dirname $0)
SCRIPT_NAME=$1
NODE_NAMES_FILTER=$2
NODE_NAMES="$($SCRIPTS_DIR/node_names $NODE_NAMES_FILTER)"

cat $SCRIPTS_DIR/$SCRIPT_NAME

echo ""
echo ""
echo ""
echo ""

read -n 1 -s -r -p "Press any key to continue..."
echo ""
echo ""

# copy script over
pushd $SCRIPTS_DIR &> /dev/null
chmod u+x "$SCRIPT_NAME"
yes | ./copy_file_to_nodes "$SCRIPT_NAME" "$NODE_NAMES_FILTER" &> /dev/null
popd &> /dev/null

# remotely run the script
parallel vagrant ssh {} -c "\~/$SCRIPT_NAME" ::: $NODE_NAMES